# Builds src/platform/mock-binary.ts: a small real Word document and a PNG for the browser
# build's demo files (so the DOCX and image viewers can be seen without the desktop app).
# Usage: python e2e/make-binary-fixtures.py
import base64, io, os, zipfile

HERE = os.path.dirname(os.path.abspath(__file__))
APP = os.path.dirname(HERE)

W = 'xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"'


def p(text, style=None, bold_prefix=None):
    ppr = f'<w:pPr><w:pStyle w:val="{style}"/></w:pPr>' if style else ''
    runs = ''
    if bold_prefix:
        runs += f'<w:r><w:rPr><w:b/></w:rPr><w:t xml:space="preserve">{bold_prefix}</w:t></w:r>'
    runs += f'<w:r><w:t xml:space="preserve">{text}</w:t></w:r>'
    return f'<w:p>{ppr}{runs}</w:p>'


def cell(t, bold=False):
    rpr = '<w:rPr><w:b/></w:rPr>' if bold else ''
    return f'<w:tc><w:p><w:r>{rpr}<w:t>{t}</w:t></w:r></w:p></w:tc>'


def row(cells, bold=False):
    return '<w:tr>' + ''.join(cell(c, bold) for c in cells) + '</w:tr>'


body = ''.join([
    p('Halloween Window Pack — Production Brief', 'Heading1'),
    p(' 30 September 2026', bold_prefix='Date:'),
    p(' Kaine, studio team', bold_prefix='Owner:'),
    p('Goal', 'Heading2'),
    p('Twelve seamless loops for shop-window projection, delivered as DXV3 and H.264 with a preview reel.'),
    p('Deliverables', 'Heading2'),
    '<w:tbl><w:tblPr><w:tblStyle w:val="TableGrid"/></w:tblPr>',
    row(['Loop', 'Length', 'Status'], bold=True),
    row(['Haunted Porch', '0:16', 'Rendered']),
    row(['Pumpkin Parade', '0:32', 'In progress']),
    row(['Ghost Choir', '0:16', 'Storyboard']),
    '</w:tbl>',
    p('Next steps', 'Heading2'),
    p('Final colour pass on Friday, then encode and upload to the store.'),
])

document = f'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document {W}><w:body>{body}</w:body></w:document>'
styles = f'''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:styles {W}>
<w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="heading 1"/></w:style>
<w:style w:type="paragraph" w:styleId="Heading2"><w:name w:val="heading 2"/></w:style>
</w:styles>'''
content_types = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
<Default Extension="xml" ContentType="application/xml"/>
<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>
<Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/>
</Types>'''
rels = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
</Relationships>'''
doc_rels = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>
</Relationships>'''

buf = io.BytesIO()
with zipfile.ZipFile(buf, 'w', zipfile.ZIP_DEFLATED) as z:
    z.writestr('[Content_Types].xml', content_types)
    z.writestr('_rels/.rels', rels)
    z.writestr('word/document.xml', document)
    z.writestr('word/styles.xml', styles)
    z.writestr('word/_rels/document.xml.rels', doc_rels)
docx = base64.b64encode(buf.getvalue()).decode()

with open(os.path.join(APP, 'src-tauri', 'icons', '128x128@2x.png'), 'rb') as f:
    png = base64.b64encode(f.read()).decode()

out = os.path.join(APP, 'src', 'platform', 'mock-binary.ts')
with open(out, 'w', encoding='utf-8', newline='\n') as f:
    f.write('// Generated by e2e/make-binary-fixtures.py: binary demo files for the browser build.\n')
    f.write('export const SAMPLE_BINARY: Record<string, string> = {\n')
    f.write(f"  'Production Brief.docx': '{docx}',\n")
    f.write(f"  'Logo.png': '{png}',\n")
    f.write('};\n')
print('wrote', out, len(docx), len(png))
